### ISSUE TITLE
Make permissions work with LuckPerms and not based on OP privelages?

### ISSUE THREAD

**Issue by mastachef** [Xwaffle1/CobblemonExtras#3]
Is it possible that the permissions can work with a permission plugin since I cant OP people on a public server would make it much easier to use if it was just recognized as a permission.

only way it works without OP is if I change the permission levels to 0 but then everyone can access the commands

they only work if the user is OP'd

cobblemonextras.command.compsee
cobblemonextras.command.compseeother
cobblemonextras.command.pc
cobblemonextras.command.pokesee
cobblemonextras.command.pokeseeother
cobblemonextras.command.pokeshout
cobblemonextras.command.poketrade
cobblemonextras.command.pokebattle
cobblemonextras.command.battle
cobblemonextras.command.comptake

Groups/users have permissions but the only way the commands will run is if I set the permission level to 0 which then just allows everyone on the server to execute the commands regardless of permissions so this is not working correctly with luckperms at least from my testing.

**Comment by KhaozFrost** [comment]
also getting this issue

**Comment by mastachef** [comment]
> perms with luckperms appear to be minecraft.command.compseeother minecraft.command.pc minecraft.command.pokesee minecraft.command.pokeseeother minecraft.command.pokeshout minecraft.command.poketrade minecraft.command.pokebattle minecraft.command.battle minecraft.command.comptake

Thank you!!
